fifa/apps/clubs/urls.py
# Core imports
from django.conf.urls import patterns, url

from .views import ClubList, ClubDetail


urlpatterns = patterns(
    '',
    url(r'^$', ClubList.as_view(), name="club_list"),
    url(r'^(?P<slug>[\w-]+)/$', ClubDetail.as_view(), name='club_detail'),
)

fifa/apps/leagues/urls.py
# Core imports
from django.conf.urls import patterns, url

from .views import LeagueList, LeagueDetail


urlpatterns = patterns(
    '',
    url(r'^$', LeagueList.as_view(), name="league_list"),
    url(r'^(?P<slug>[\w-]+)/$', LeagueDetail.as_view(), name='league_detail'),
)

fifa/apps/nations/urls.py
# Core imports
from django.conf.urls import patterns, url

from .views import NationList, NationDetail


urlpatterns = patterns(
    '',
    url(r'^$', NationList.as_view(), name="nation_list"),
    url(r'^(?P<slug>[\w-]+)/$', NationDetail.as_view(), name='nation_detail'),
)

fifa/apps/players/urls.py
from django.conf.urls import patterns, url

from .views import PlayerList, PlayerDetail

urlpatterns = patterns(
    '',
    url(r'^$', PlayerList.as_view(), name='player_list'),
    url(r'^(?P<slug>[\w-]+)/$', PlayerDetail.as_view(), name='player_detail'),
)

fifa/apps/profiles/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(
        r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'profiles/login.html'
        },
        name='login'
    ),

    url(
        r'^logout/$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/'
        },
        name='logout'
    ),

    # url(
    #     r'^register/$',
    #     'django.contrib.auth.views.r'
    # ),

    url(
        r'^password-change/$',
        'django.contrib.auth.views.password_change',
        {
            'post_change_redirect': '/profiles/password-change/success/'
        },
        name='password-change'
    ),

    url(
        r'^password-change/success/$',
        'django.contrib.auth.views.password_change_done',
        name='password-change-success'
    ),

    url(
        r'^password-reset/$',
        'django.contrib.auth.views.password_reset',
        {
            'post_reset_redirect': '/profiles/password-reset/done/'
        },
        name='password-reset'
    ),

    url(
        r'^password-reset/next/$',
        'django.contrib.auth.views.password_reset_done',
        name='password-reset-done'
    ),

    url(
        r'^password-reset/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'
    )

    # TODO: Password reset urls
)

fifa/apps/squads/urls.py
# Core imports
from django.conf.urls import patterns, url

from .views import SquadList, SquadDetail, SquadBuilder


urlpatterns = patterns(
    '',
    url(r'^$', SquadList.as_view(), name='squad_list'),
    url(r'^builder/$', SquadBuilder.as_view(), name='squad_builder'),
    url(r'^(?P<slug>[a-z0-9\-]+)/$', SquadDetail.as_view(), name='squad_detail'),
)

fifa/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(
        r'^$',
        TemplateView.as_view(template_name='base.html'),
        name='homepage'
    ),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^clubs/', include('apps.clubs.urls', namespace='clubs')),

    url(r'^leagues/', include('apps.leagues.urls', namespace='leagues')),

    url(r'^nations/', include('apps.nations.urls', namespace='nations')),

    url(r'^players/', include('apps.players.urls', namespace='players')),

    url(r'^squads/', include('apps.squads.urls', namespace='squads')),

    url(r'^profiles/', include('apps.profiles.urls', namespace='profiles')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url("^404/$", TemplateView.as_view(template_name="404.html")),
        url("^500/$", TemplateView.as_view(template_name="500.html")),
    ) + static(
        settings.JSPM_URL, document_root=settings.JSPM_ROOT
    ) + static(
        settings.ASSET_URL, document_root=settings.ASSET_ROOT
    )

fifa/apps/clubs/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Club(models.Model):
    created = models.DateTimeField(
        auto_now_add=True
    )

    modified = models.DateTimeField(
        auto_now=True
    )

    asset_id = models.PositiveIntegerField(
        unique=True,
        db_index=True
    )

    name = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    name_abbr = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    league = models.ForeignKey(
        'leagues.League',
        to_field='asset_id',
        related_name='clubs'
    )

    slug = models.CharField(
        max_length=50,
        blank=True
    )

    players_count = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_average_rating = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_inform = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_gold = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_silver = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_bronze = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_gk = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_def = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_mid = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    players_att = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    def __str__(self):
        return self.name_abbr

    class Meta:
        ordering = ['-players_average_rating', 'name']
        verbose_name = 'club'
        verbose_name_plural = 'clubs'

    def get_absolute_url(self):
        return reverse('clubs:club_detail', kwargs={'slug': self.slug})

fifa/apps/players/forms.py
from django import forms

from .models import Player
from ..clubs.models import Club
from ..leagues.models import League
from ..nations.models import Nation

default_all_choice = [
    ('all', 'All')
]

small_range_choices = [
    (x, x) for x in range(1, 6)
]

large_range_choices = [
    (x, x) for x in range(1, 100)
]

workrate_choices = default_all_choice + [
    ('high', 'High'),
    ('med', 'Medium'),
    ('low', 'Low')
]

prices_platform_choices = [
    ('xbox', 'Xbox'),
    ('psn', 'PSN'),
    ('pc', 'PC')
]

position_choices = default_all_choice + [
    ('gk', 'GK'),
    ('rwb', 'RWB'),
    ('rb', 'RB'),
    ('cb', 'CB'),
    ('lb', 'LB'),
    ('lwb', 'LWB'),
    ('cdm', 'CDM'),
    ('cm', 'CM'),
    ('cam', 'CAM'),
    ('rm', 'RM'),
    ('rw', 'RW'),
    ('rf', 'RF'),
    ('lm', 'LM'),
    ('lw', 'LW'),
    ('lf', 'LF'),
    ('cf', 'CF'),
    ('st', 'ST')
]


class PlayerFilterForm(forms.Form):
    rating_min = forms.ChoiceField(
        choices=large_range_choices,
        initial=1
    )

    rating_max = forms.ChoiceField(
        choices=reversed(large_range_choices),
        initial=99
    )

    player_type = forms.ChoiceField(
        initial='All'
    )

    skill_min = forms.ChoiceField(
        choices=small_range_choices,
        initial=1
    )

    skill_max = forms.ChoiceField(
        choices=reversed(small_range_choices),
        initial=5
    )

    weak_min = forms.ChoiceField(
        choices=small_range_choices,
        initial=1
    )

    weak_max = forms.ChoiceField(
        choices=reversed(small_range_choices),
        initial=5
    )

    workrate_def = forms.ChoiceField(
        choices=workrate_choices,
        initial='All'
    )

    workrate_att = forms.ChoiceField(
        choices=workrate_choices,
        initial='All'
    )

    preferred_foot = forms.ChoiceField(
        initial='All'
    )

    prices_platform = forms.ChoiceField(
        choices=prices_platform_choices,
        initial='Xbox'
    )

    prices_min = forms.CharField(
        min_length=1,
        max_length=8,
        initial=0
    )

    prices_max = forms.CharField(
        min_length=1,
        max_length=8,
        initial=1000000
    )

    positions = forms.MultipleChoiceField(
        choices=position_choices,
        initial='All'
    )

    clubs = forms.ModelChoiceField(
        queryset=Club.objects.all(),
        empty_label='All',
        required=False,
        initial='All'
    )

    leagues = forms.ModelChoiceField(
        queryset=League.objects.all(),
        empty_label='All',
        required=False,
        initial='All'
    )

    nations = forms.ModelChoiceField(
        queryset=Nation.objects.all(),
        empty_label='All',
        required=False,
        initial='All'
    )

    def __init__(self, *args, **kwargs):
        super(PlayerFilterForm, self).__init__()

        player_type_choices = default_all_choice + [
            (x, x.capitalize() if x != 'team of the week' else 'TOTW') for x in
            Player.objects.order_by().values_list(
                'player_type',
                flat=True
            ).distinct()
        ]

        preferred_foot_choices = default_all_choice + [
            (x, x) for x in Player.objects.order_by().values_list(
                'preferred_foot',
                flat=True
            ).distinct()
        ]

        self.fields['player_type'].choices = player_type_choices
        self.fields['preferred_foot'].choices = preferred_foot_choices

fifa/apps/clubs/views.py
from django.views.generic import ListView, DetailView
from apps.players.models import Player

from apps.core.functions.detailview_pagination import detailview_pagination
from .models import Club


class ClubList(ListView):
    model = Club
    paginate_by = 50


class ClubDetail(DetailView):
    model = Club

    def get_context_data(self, **kwargs):
        context = super(ClubDetail, self).get_context_data()

        players = Player.objects.filter(
            club=self.get_object()
        ).select_related(
            'club',
            'league',
            'nation'
        )

        context['players'] = detailview_pagination(self, players)

        return context

fifa/apps/leagues/views.py
from django.views.generic import DetailView, ListView

from .models import League
from apps.core.functions.detailview_pagination import detailview_pagination
from apps.players.models import Player


class LeagueList(ListView):
    model = League
    paginate_by = 50


class LeagueDetail(DetailView):
    model = League

    def get_context_data(self, **kwargs):
        context = super(LeagueDetail, self).get_context_data()

        players = Player.objects.filter(
            league=self.get_object()
        ).select_related(
            'club',
            'league',
            'nation'
        )

        context['players'] = detailview_pagination(self, players)

        return context

fifa/apps/nations/views.py
from django.views.generic import ListView, DetailView

from apps.core.functions.detailview_pagination import detailview_pagination
from apps.players.models import Player
from .models import Nation


class NationList(ListView):
    model = Nation
    paginate_by = 50


class NationDetail(DetailView):
    model = Nation

    def get_context_data(self, **kwargs):
        context = super(NationDetail, self).get_context_data()

        players = Player.objects.filter(
            nation=self.get_object()
        ).select_related(
            'club',
            'league',
            'nation'
        )

        context['players'] = detailview_pagination(self, players)

        return context

fifa/apps/players/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin, CreateView

from .forms import PlayerFilterForm
from .models import Player


class SortMixin(object):
    pass


class PlayerViewMixin(object):
    model = Player

    def get_queryset(self):
        return super(PlayerViewMixin, self).get_queryset().prefetch_related(
            'club',
            'league',
            'nation'
        )


class PlayerList(PlayerViewMixin, FormMixin, ListView):
    paginate_by = 50
    template_name = 'players/player_list.html'

    def get_context_data(self, **kwargs):
        context = super(PlayerList, self).get_context_data()

        if self.request.GET:
            context['form'] = PlayerFilterForm(self.request.GET)
        else:
            context['form'] = PlayerFilterForm()

        return context

    def get_queryset(self):
        qs = super(PlayerList, self).get_queryset()
        parameters = {
            'rating_min': {
                'overall_rating__gte': self.request.GET.get('rating_min')
            },
            'rating_max': {
                'overall_rating__lte': self.request.GET.get('rating_max')
            },
            'player_type': {
                'player_type': self.request.GET.get('player_type')
            },
            'skill_min': {
                'skill_moves__gte': self.request.GET.get('skill_min')
            },
            'skill_max': {
                'skill_moves__lte': self.request.GET.get('skill_max')
            },
            'weak_min': {
                'weak_foot__gte': self.request.GET.get('weak_min')
            },
            'weak_max': {
                'weak_foot__lte': self.request.GET.get('weak_max')
            },
            'workrate_def': {
                'workrate_def': self.request.GET.get('workrate_def')
            },
            'workrate_att': {
                'workrate_att': self.request.GET.get('workrate_att')
            },
            'preferred_foot': {
                'preferred_foot': self.request.GET.get('preferred_foot')
            },
            # 'pricesplatform': self.request.GET.get('prices_platform'),
            # 'pricesmin': self.request.GET.get('prices_min'),
            # 'pricesmax': self.request.GET.get('prices_max'),
            # 'clubs': self.request.GET.get('clubs'),
            # 'leagues': self.request.GET.get('leagues'),
            # 'nations': self.request.GET.get('nations')
        }

        params = filter(lambda x: self.request.GET.get(x) != 'all', parameters)

        if self.request.GET:
            for param in params:
                qs = qs.filter(
                    **parameters[param]
                )

        return qs


class PlayerDetail(PlayerViewMixin, DetailView):
    pass

fifa/apps/squads/views.py
from django.views.generic import ListView, DetailView, CreateView

from .models import Squad
from .forms import SquadBuilderForm
from apps.players.models import Player


class SquadList(ListView):
    model = Squad
    paginate_by = 25


class SquadDetail(DetailView):
    model = Squad

    # TODO: Reduce the number of queries, it's quick but surely we can reduce them?


class SquadBuilder(CreateView):
    form_class = SquadBuilderForm
    template_name = 'squads/squad_builder.html'

    def form_valid(self, form):
        obj = form.save(commit=False)

        if self.request.user.is_authenticated():
            obj.user = self.request.user
        else:
            # TODO: Potentially save squad to session and assign it to their
            # account if they make one in the session
            self.request.session['squad'] = obj

        form_players = {
            'squad_1': form.data['squad_1_form'],
            'squad_2': form.data['squad_2_form'],
            'squad_3': form.data['squad_3_form'],
            'squad_4': form.data['squad_4_form'],
            'squad_5': form.data['squad_5_form'],
            'squad_6': form.data['squad_6_form'],
            'squad_7': form.data['squad_7_form'],
            'squad_8': form.data['squad_8_form'],
            'squad_9': form.data['squad_9_form'],
            'squad_10': form.data['squad_10_form'],
            'squad_11': form.data['squad_11_form'],
        }

        fields = {}
        for num in range(1, 12):
            fields['squad_{}'.format(num)] = [
                'squad_{}_position'.format(num),
                'squad_{}_chemistry'.format(num),
                'squad_{}_chemistry_style'.format(num),
                'squad_{}_loyalty'.format(num),
            ]

        submitted_players = {k: v for k, v in form_players.items() if v != ''}

        if submitted_players:
            players = [player for player in Player.objects.filter(
                id__in=submitted_players.values()
            )]

            for k, v in submitted_players.items():
                for player in players:
                    if int(v) == int(player.id):
                        setattr(obj, k, player)
                        setattr(obj, '{}_position'.format(k), player.position)
                        setattr(obj, '{}_chemistry'.format(k), form.data['{}_chemistry_form'.format(k)])
                        setattr(obj, '{}_chemistry_style'.format(k), form.data['{}_chemistry_style_form'.format(k)])
                        setattr(obj, '{}_loyalty'.format(k), form.data.get('{}_loyalty_form'.format(k), ''))

        obj.save()

        return super(SquadBuilder, self).form_valid(form)

fifa/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>

        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
        <meta name="description" content="{% block meta_description %}{% endblock meta_description %}">
        <meta name="robots" content="{% block meta_robots %}{% endblock meta_robots %}">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

        <!-- Styles -->
        <link href="{% static 'css/screen.css' %}" rel="stylesheet" type="text/css">

        <title>{% block title %}{% endblock title %}</title>

        {% block extra_styles %}{% endblock %}
        {% block head_js %}{% endblock %}

        <link rel="shortcut icon" href="/static/img/favicon.png" />
        <link rel="apple-touch-icon" href="/static/img/homescreen.png">

        <script src="//use.typekit.net/ajz1shi.js"></script>
        <script>try{Typekit.load();}catch(e){}</script>

        <!--[if lt IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>

    <body class="{% block body_class %}{% endblock body_class %}">
        {% block top_bar %}
            <div class="top-bar">
                <div class="row">
                    <div class="medium-3 columns text-center">
                        <a class="top-bar__logo" href="#">
                            Logo
                        </a>
                    </div>
                    <div class="medium-21 columns">
                        <nav class="pull-left">
                            <ul class="nav nav--inline">
                                <li class="nav__item">
                                    <a class="nav__item-link" href="{% url 'players:player_list' %}">Players</a>
                                </li>
                                <li class="nav__item">
                                    <a class="nav__item-link" href="{% url 'squads:squad_builder' %}">Squad Builder</a>
                                </li>
                                <li class="nav__item">
                                    <a class="nav__item-link" href="{% url 'squads:squad_list' %}">Squads</a>
                                </li>
                                <li class="nav__item">
                                    <a class="nav__item-link" href="{% url 'clubs:club_list' %}">Clubs</a>
                                </li>
                                <li class="nav__item">
                                    <a class="nav__item-link" href="{% url 'leagues:league_list' %}">Leagues</a>
                                </li>
                                <li class="nav__item">
                                    <a class="nav__item-link" href="{% url 'nations:nation_list' %}">Nations</a>
                                </li>
                                <li class="nav__item">
                                    <a class="nav__item-link" href="#">News</a>
                                </li>
                                <li class="nav__item">
                                    <a class="nav__item-link" href="#">Community</a>
                                </li>
                            </ul>
                        </nav>
                        <nav class="pull-right">
                            <ul class="nav nav--inline">
                                {% if user.is_authenticated %}
                                    <li class="nav__item">
                                        <a class="nav__item-link" href="#">{{ user.display_name }}</a>
                                    </li>
                                    <li class="nav__item">
                                        <a class="nav__item-link" href="">
                                            <i class="fa fa-user"></i>
                                        </a>
                                    </li>
                                    <li class="nav__item">
                                        <a class="nav__item-link" href="">
                                            <i class="fa fa-users"></i>
                                        </a>
                                    </li>
                                    <li class="nav__item">
                                        <a class="nav__item-link" href="">
                                            <i class="fa fa-calendar"></i>
                                        </a>
                                    </li>
                                    <li class="nav__item">
                                        <a class="nav__item-link" href="{% url 'profiles:logout' %}">Logout</a>
                                    </li>
                                {% else %}
                                    <li class="nav__item">
                                        <a class="nav__item-link" href="{% url 'profiles:login' %}">Login</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        {% endblock top_bar %}
        {% block top_strap %}
            <div class="top-strap">
                <div class="row">
                    <div class="medium-24 columns">

                    </div>
                </div>
            </div>
        {% endblock top_strap %}
        {% block controls_top %}
            <div class="controls controls--top">
                Controls top
            </div>
        {% endblock controls_top %}
        {% block primary_content %}
            g
        {% endblock primary_content %}
        {% block end_js %}{% endblock %}

        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>